/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/AnshulAngaria/ClusterOP/pkg/api/AnshulAngaria/v1alpha1"
	scheme "github.com/AnshulAngaria/ClusterOP/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterOPsGetter has a method to return a ClusterOPInterface.
// A group's client should implement this interface.
type ClusterOPsGetter interface {
	ClusterOPs(namespace string) ClusterOPInterface
}

// ClusterOPInterface has methods to work with ClusterOP resources.
type ClusterOPInterface interface {
	Create(ctx context.Context, clusterOP *v1alpha1.ClusterOP, opts v1.CreateOptions) (*v1alpha1.ClusterOP, error)
	Update(ctx context.Context, clusterOP *v1alpha1.ClusterOP, opts v1.UpdateOptions) (*v1alpha1.ClusterOP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterOP, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterOPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterOP, err error)
	ClusterOPExpansion
}

// clusterOPs implements ClusterOPInterface
type clusterOPs struct {
	client rest.Interface
	ns     string
}

// newClusterOPs returns a ClusterOPs
func newClusterOPs(c *AnshulAngariaV1alpha1Client, namespace string) *clusterOPs {
	return &clusterOPs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterOP, and returns the corresponding clusterOP object, and an error if there is any.
func (c *clusterOPs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterOP, err error) {
	result = &v1alpha1.ClusterOP{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterops").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterOPs that match those selectors.
func (c *clusterOPs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterOPList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterOPList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterOPs.
func (c *clusterOPs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterOP and creates it.  Returns the server's representation of the clusterOP, and an error, if there is any.
func (c *clusterOPs) Create(ctx context.Context, clusterOP *v1alpha1.ClusterOP, opts v1.CreateOptions) (result *v1alpha1.ClusterOP, err error) {
	result = &v1alpha1.ClusterOP{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterOP).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterOP and updates it. Returns the server's representation of the clusterOP, and an error, if there is any.
func (c *clusterOPs) Update(ctx context.Context, clusterOP *v1alpha1.ClusterOP, opts v1.UpdateOptions) (result *v1alpha1.ClusterOP, err error) {
	result = &v1alpha1.ClusterOP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterops").
		Name(clusterOP.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterOP).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterOP and deletes it. Returns an error if one occurs.
func (c *clusterOPs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterops").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterOPs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterops").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterOP.
func (c *clusterOPs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterOP, err error) {
	result = &v1alpha1.ClusterOP{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterops").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
