apiVersion: api.core.clusterop.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  name: test-cluster
  region: "nyc1"
  version: "1.27.4-do.0"
  tokenSecret: "default/dosecret"
  nodePools:
    - count: 3
      name: "dummy-nodepool"
      size: "s-1vcpu-2gb"
  # TODO(user): Add fields here
